# Generated by Django 2.2.5 on 2020-11-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='short_title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
