# Generated by Django 2.2.5 on 2020-11-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_game_short_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='short_title',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
