# Generated by Django 2.2.5 on 2020-11-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0003_auto_20201110_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='short_title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
