# Generated by Django 2.2.5 on 2020-11-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0004_auto_20201110_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='short_title',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
