"""
Django settings for martialmentor project.
Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/


########## -------- This is the production settings.py -------- ##########


"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# Read SECRET_KEY from text file:
with open('/home/MateoElGoron/secret_key.txt') as f:
    SECRET_KEY = f.read().strip()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['MateoElGoron.eu.pythonanywhere.com']

# Application definition

INSTALLED_APPS = [
    'mentor.apps.MentorConfig',     # put app first to override things like default templates for password reset

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'martialmentor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'mentor/templates/mentor'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'martialmentor.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

db_password = ''
with open('/home/MateoElGoron/db_ps.txt') as f:
    db_password = f.read().strip()

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'MateoElGoron$mentor_db',
        'USER': 'MateoElGoron',
        'PASSWORD': db_password,
        'HOST': 'MateoElGoron.mysql.eu.pythonanywhere-services.com',
        'TEST': {
            'NAME': 'MateoElGoron$test_mentor_db',
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

# URL of static files:
STATIC_URL = '/static/'

# Filepath where static files are copied to during collectstatic:
STATIC_ROOT = os.path.join(BASE_DIR, 'root')

# Directories which the collectstatic command searches for static files:
# Note: static dirs in apps are detected automatically, so don't need to be pointed to in this list.
# STATICFILES_DIRS = [
# os.path.join(BASE_DIR, 'static'),
# ]


# Where users are redirected to upon login:
LOGIN_REDIRECT_URL = 'mentor:index'
LOGOUT_REDIRECT_URL = 'mentor:index'


# Email:
EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
EMAIL_FILE_PATH = os.path.join(BASE_DIR, 'sent_emails')
